version: '2'
services:
  mysql:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp=1
    container_name: mysql_container
    env_file:
     - ./api/api.env
    environment:
      - MYSQL_ROOT_PASSWORD=jhub
      - MYSQL_DATABASE=jupyterhub
      - MYSQL_USER=jupyterhub
      - MYSQL_PASSWORD=jhub
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql



  hub:
    depends_on:
      - mysql
    build: .
    container_name: jupyterhub
    environment:
     - TERM=xterm
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - 8080:8000
    links:
      - mysql:mysql
    restart: always
    
    
volumes:
  mysql-data:
    driver: local